#!/bin/sh
pwsh -NoProfile -Command '
  $result = Invoke-DelphiIncVer \
    -File "source/Delphi.Forms.Info.pas" \
    -IncverTarget "Text" \
    -IncverStyle "WinVer" \
    -IncverPart "patch" \
    -IncverPattern "(\d+\.\d+\.\d+\.\d+)"
  if (-not $result.Success) { exit 1 }
'
git add source/Delphi.Forms.Info.pas
